services:
  music-assistant-skill:
    build: .
    environment:
      - SKILL_HOSTNAME=<hostname> #required
      - MA_HOSTNAME=<hostname> #optional, if only using APL devices
      - APP_USERNAME=/run/secrets/APP_USERNAME #optional
      - APP_PASSWORD=/run/secrets/APP_PASSWORD #optional
      - PORT=5000 #optional
      - DEBUG_PORT=0 # enable only for local debugging
      - LWA_CLIENT_ID= # one-time security profile registration
      - LWA_CLIENT_SECRET=/run/secrets/LWA_CLIENT_SECRET
      - LWA_REDIRECT_URI=https://alexa.example.com/ma-alexa-skill/setup/oauth/callback
      - SKILL_CERTIFICATE_TYPE=Trusted
      - SKILL_DEPLOYMENT_PATH=/data/skill-deployment.json
      - LOCALE=en-US # optional: skill locale (e.g. en-US, en-GB, de-DE)
      - AWS_DEFAULT_REGION=us-east-1 #optional
      - TZ=America/Chicago # set container timezone (override as needed)
    secrets:
      - APP_USERNAME
      - APP_PASSWORD
      - LWA_CLIENT_SECRET
    ports:
      - 5000:5000 # Must match PORT
    volumes:
      - ./ask_data:/root/.ask
      - ./deployment_data:/data
    restart: no

secrets:
  APP_USERNAME:
    file: ./secrets/app_username.txt
  APP_PASSWORD:
    file: ./secrets/app_password.txt
  LWA_CLIENT_SECRET:
    file: ./secrets/lwa_client_secret.txt
